modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="cuisine"
version="${file.jarVersion}"
displayName="Cuisine"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cuisine2"
description=""

[[dependencies.cuisine]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.6.3, 2.10)"
    ordering="BEFORE"
    side="BOTH"
